version: "3.8"

services:
  jekyll:
    image: jekyll/jekyll
    command: sh -c "bundle config set --local path 'vendor/bundle' && bundle install && bundle exec jekyll serve --host 0.0.0.0"
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
